# Computer Vision Basics with openCV

### Import statements

In [2]:
import cv2
import numpy as np

### Check your openCV version

In [3]:
cv2.__version__

'3.4.2'

## Computer Vision Basics

### Load and Image

In [13]:
# Declare a variable with the path to your image
path = "M6_Computer_Vision\01. Basics of computer vision"
%pwd 

'c:\\Users\\pgsin\\Documents\\AI_ENGINEERING\\Striving\\M6_Computer_Vision\\01. Basics of computer vision'

In [7]:
# Load the image with openCV
org_img= cv2.imread('Wyoming_Ave.jpg')

[Hint](# "You will need to use cv2.imread")

### Check the image type

In [8]:
# What is the image type? -> typet
type(org_img)

numpy.ndarray

[Hint](# "Just use the python type function")

In [14]:
# Print the value of the pixels of the image
print(org_img)

[[[250 248 240]
  [247 245 237]
  [246 244 236]
  ...
  [147 145 151]
  [137 135 141]
  [142 140 146]]

 [[241 239 231]
  [241 239 231]
  [244 242 234]
  ...
  [124 122 128]
  [137 135 141]
  [141 139 145]]

 [[239 237 229]
  [238 236 228]
  [242 240 232]
  ...
  [125 121 127]
  [142 138 144]
  [163 159 165]]

 ...

 [[ 15  13  13]
  [  9   7   7]
  [ 16  11  12]
  ...
  [ 13   9   8]
  [ 13   9   8]
  [  8   4   3]]

 [[  9   7   7]
  [  8   6   6]
  [ 13  11  11]
  ...
  [ 13   9   8]
  [ 14  10   9]
  [  9   5   4]]

 [[  8   6   6]
  [  8   6   6]
  [ 12  10  10]
  ...
  [ 15  11  10]
  [ 12   8   7]
  [ 15  11  10]]]


[Hint](# "Just use the python print function")

### Show the image using openCV

In [16]:
# Lets now see the image! dont forget to call destroyAllWindows!
cv2.imshow('frutta', org_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

[Hint](# "You need to use imshow, waitkey and destroyAllWindows")

### Now lets display unsing matplotlib

In [ ]:
# Import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# Choose a pyplot figsize to make images fit nicely into the notebook


# Now display the image with plt


### Lets fix the colors

In [ ]:
# Does your image look ok? are the colors the right ones?, if not, lets fix it!
# Remember that openCV will load images using BGR rather than RGB
# Change the image to RGB and diplay it again with plt


[Hint](# "use cvtColor") 

### What is the shape of the image?

In [ ]:
# Check the image shape


### Lets make it grayscale

In [ ]:
# Load the the image in grayscale, what are the 2 ways you can do that?


In [ ]:
# Now load an image in color and then transform it to grayscale


### What is the shape now?

In [ ]:
# Check the grayscale shape


### How does it look like?

In [ ]:
# Display the grayscale image with matplotlib, how does it look?


### We need to indicate the colormap

In [ ]:
# Display the grayscale image with matplotlib, make sure to include the colormap so it really is grayscale


### Cropping an image

In [ ]:
# Lets now crop a Region of Interest of an image, load and image and crop different parts of it


In [ ]:
# Save to disk the cropped areas


### To edit an image making a copy of it is always a good idea!

In [ ]:
# Load an image and then make a copy of it

[Hint](# "use the numpy function ") 

## Annotating images

### Rectangles

In [ ]:
# Draw green rectangle on top of a region of interest in your image


[Hint](# "You will need to use the cv2 function rectangle(img, pt1, pt2, color, thickness) -> img") 

### Adding text to images

In [ ]:
# Make a copy of your image and then write some text on top of the image


[Hint](# "You will need to use cv2 putText function -> putText(img, text, coordinates, fontFace, fontScale, color, thickness, lineType). For fonts check the enum cv2.FONT_HERSHEY_") 

Now that you know how to load annotate and save images lets start manually annotating some images

![](annotations.jpg)

In [ ]:
# Load as many images as you like and start annotating objects in the image, 
# Before annotating the images make a copy of the image so we keep the original without changes
# Use the format proposed in the example above



In [ ]:
# Display the images that you have annotated above, both versions, the original one and the annotated one


# Mini Projects

With all that you accomplished to do above you are now ready to do your first mini project!, you might need to learn some more new things to accomplish some of the harder levels below, it is very important to get used to the openCV docs 

## Meme creator

### Level 1
1. Create a basic Meme creator with one image and a short line of text, using any openCV font

### Level 2
1. Use the classic meme font (impact)

### Level 3
1. Improve it by adding 2 to 3 lines with the text on the top of the image and the bottom of the image
1. Make the text in white and with black contours

### Level 4
1. Make the text center automatically [Hint](# "getTextSize") 
1. If the text is too long it should wrap the text in as many lines as needed



## QR Reader

### Level 1
1. Researn on the openCV docs and learn about QRCodeDetector
1. Grab any QR code from google images for example this one: ![](https://blog-trycontechnologi.netdna-ssl.com/blog/qrbatch/wp-content/uploads/sites/7/2019/07/ID-Card-with-QR-Code-2-1.png) or any other. 
1. Detect the code using QRCodeDetector
1. Print QR detected if a QR has been detected in the image

### Level 2
1. Decode and print the decoded text
1. Draw a rectangle around the QR code that has been detected and show it on screen
1. Save the QR region of the image to disk
