In [1]:
import numpy as np 


# Q1
#### I have both long and short call options positions (with different strikes) on the same underlying with the same notional, both expiring tomorrow.
#### My position is exposed to market risk.

# Q2
#### Long put position vs. long call (both exchange-traded) position:
#### Both position increase in value when volatility goes up(keeping all other variables constant)
#### Contract terms for both are standardized

# Q4
#### What is the idea behind the Close-Out and Netting provisions of the ISDA Master agreement and how does it affect the counterparty risk?
#### In case of a credit event one counterparty can cancel all outstanding transactions under the Master agreement
#### The counterparty risk is potentially reduced when there are several deals outstanding

# Q5
#### I have both long and short forward positions on the same underlying with the same notional, both expiring tomorrow, and hence I face a non-trivial market risk with respect to the underlying.
####  The exposure is zero, and there is no market risk.


# Q6
#### The theoretical forward price decreases with maturity. Assume that the risk-free rate is positive
####  Yes, it is possible, when the present value of benefits is sufficiently higher than the present value of costs for all maturities.
#### It is possible for FX forwards when foreign interest rate is higher than the home currency rate.

# Q7
#### Cost of carry method of pricing forward contracts
#### Can be applied to price foreign exchange forwards.
#### Can be applied with annually compounded rates.

# Q8
#### A short forward on silver for delivery in twelve months is entered into at the price of per troy ounce (oz t). The volume of the contract is 100 oz t. Current spot price is . Storing silver for a six-month period is charged 0.03 $/oz t at the end of each period (incuding the date of delivery). Interest rates are 5% per annum, quarterly compounded.
#### Part A: The forward price is off-market. Find the fair spot price (spot price that would justify the observed forward price), and how much you pay or receive for establishing the forward position under given conditions.


In [8]:
def sol3_3A():
 """ 
 return a numpy array with two values: 
 spot and intial cash-flow (negative if you pay and positive otherwise)
 """ 
 
 # preallocate the numpy array - replace with your answer 
 ans = np.full(2,np.nan)
 
 ### BEGIN SOLUTION
 # 1. The value of the forward contract at inception is 0 
 # The fair spot price of silver S0 can be backed out of the forward price F012
 # PV(F012) = S0 + PV(Holding Costs) - PV(Benefits) -> hence, the S0 = ... 
 r012 = 0.05 # rate
 freq = 4 # compounding frequency
 F012 = 15 # current forward
 HC = 0.03 # holding costs per 6 months
 S0 = 13
 Notional = 100
 LongShort = -1 # indicator of long vs short position
 # PV of the forward 
 df = 1/(1+r012/freq) # discount factor per period
 PV_F012 = F012*df**4
 
 # PV of holding costs in 6 and 12 months
 PV_HC = HC*(df**4 + df**2)
 
 # compute S0fair
 S0fair = PV_F012 - PV_HC
 
 # if S0fair is higher than current spot, then by selling this forward 
 # you make money "automatically" -- thus, you need to compensate
 CurrValue = (S0fair - S0)*LongShort*Notional
 
 ans = np.array([S0fair,CurrValue])
 ### END SOLUTION
 return ans
sol3_3A()


array([  14.21505457, -121.50545683])

#### Part B: Six months later, the spot price of silver has gone up to $17 per troy ounce, and the interest rate is now 7% p.a. with the same compounding as before. What are the current forward price for the same delivery date as before and the current market value of the forward position entered into six months before?


In [10]:
def sol3_3B():
 """ 
 return a numpy array with two values: 
 current forward price and current market value of the existing forward posision
 """ 
 # preallocate the numpy array - replace with your answer 
 ans = np.full(2,np.nan)
 
 ### BEGIN SOLUTION
 # 2. Compute new forwrd price, future PNL, discount 
 # to today to get the value of PNL now
 # PV(F612) = S6 + PV(Holding Costs) - PV(Benefits)
 # F612 = FV(S6) + FV(Holding Costs) - FV(Benefits)
 
 r612 = 0.07 # new rate 
 freq = 4 # compounding frequency
 F012 = 15 # delivery price
 HC = 0.03 # holding costs per 6 months
 S6 = 17 # asset spot price at t = 6 
 Notional = 100
 LongShort = -1 # indicator of long vs short position
 
 df1 = 1/(1+r612/freq) # discount factor per componding period
 F612 = S6/df1**2 + HC
 # future PNL discounted for two periods 
 # we are short forward at F012, so if the new 
 # forward price is lower, we make money
 Pos_VAL = LongShort*Notional*(F612 - F012)*df1**2
 
 ans = np.array([F612,Pos_VAL])
 ### END SOLUTION
 return ans
sol3_3B()

array([  17.63020625, -254.05103562])

# Q9
#### You are bullish on volatility and bullish on the underlying asset. What set of instruments would not contradict your strategy? Select all that apply
#### . Long call and short put with the same strike K.


# Q10 
#### Asset is currently trading at 20, and for an out-the-money call option (strike = 22) expiring in three months you pay USD 5 corresponding to the implied volatility of 40%. In three months the asset price is 25 and the implied volatility goes down to 30%. What is your profit & loss on the option position?
###  -2


# Q11
#### ABC stock is currently at 100. In one year, the price will either increase by 10% or decrease by 10%. There is another asset H2O available, that pays the value of ABC + 5 in each of the two states of the world. The riskfree deposit pays rate of return of 5% p.a. with annual compounding. Consider a H2O2 option that delivers a payoff of 110 = 105 + 5 in the up-state and 90 = 105 - 15 in the down-state.
### To replicate H2O2 I can use any two assets from the available ones.
### The price of H2O2 is equal to 100.


# Q12
#### You have two non-redundand risky assets (A1 and A2) at your disposal, and next period uncertainty can bedescribed by two states of nature (up and down). A1 costs 10 and pays 10 and 12 in states 1 and 2,respectively. A2 costs 1 and pays -3 and 3 in states 1 and 2, respectively. In addition, there is a risk-free money-market account (MM) that pays 10 in both states of nature.
#### Part A:
#### What is the payoff matrix for the two risky assets at your disposal. Order the assets so that at position 0 you
#### have A1, and states such that at position 0 you have state 1.

In [15]:
def sol4_4A():
 """ 
 Return the payoff matrix as numpy array of dimension NxK = 2x2, 
 where N is number of risky assets and K is number of states 
 """ 
 # preallocate the numpy array - replace with your answer 
 ans = np.full((2,2),np.nan)
 
 ### BEGIN SOLUTION
 A1 = np.array([10,12])
 A2 = np.array([-3,3])
 ans = np.vstack([A1,A2])
 ### END SOLUTION
 return ans
sol4_4A()


array([[10, 12],
       [-3,  3]])

#### Part B: Create a portfolio that replicates the risk-free MM. Compute the price of the MM and the risk-free rate per period.


In [16]:
import numpy.linalg as npl
def sol4_4B():
 """ 
 Return three outputs:
 1. numpy array with the replicating portfolio: ptf
 2. price of the MM as a number (numpy float): price
 3. risk-free rate per period as a decimal (e.g., 0.05 for 5% rate) 
 number (numpy float): rate 
 """ 
 # pre-allocate variables to return -- replace with your own the answers 
 ptf = np.full(2, np.nan)
 price = np.full(2, np.nan)
 rate = 0.0
 
 ### BEGIN SOLUTION
 # create the payoff matrix 
 A1 = np.array([10,12])
 A2 = np.array([-3,3])
 X = np.vstack([A1,A2])
 
 # create the vector of prices 
 prc = np.array([10,1])
 # create the payoff vector for the MM 
 cf = np.array([10,10])
 
 # solve the system of equations X.T@ptf = cf
 ptf = npl.inv(X.T)@cf
 
 # compute the price of the replicating portfolio as the dot product
 price = prc@ptf
 
 # compute the rate 
 rate = cf[0]/price-1
 
 # you certaintly could have hard-coded the answer directly -- 
 # in this case you need to describe how you got your solution in 
 # the Markdown cell below!
 
 ### END SOLUTION
 return ptf, price, rate
sol4_4B()


(array([ 0.90909091, -0.3030303 ]), 8.787878787878787, 0.13793103448275867)

# Part C:
#### Assume now that the economy is slightly different: asset A1 is still the same (payoffs and the price), risk-free MM account costs 10 now and pays 11 in both states of nature, asset A2 pays the same as before (-3 and 3) instates 1 and 2, but the price of A2 is unknown. Find risk-neutral probabilities in this economy and the price of asset A2 using risk-neutral valuation approach.

In [18]:
def sol4_4C():
 """ 
 Return two outputs:
 1. numpy array with the two risk-neutral probabilities 
 ordered as state1, state2: Q
 2. price of A2 as a number (numpy float): price
 """ 
 # pre-allocate variables to return -- replace with your own the answers 
 Q = np.full(2, np.nan)
 price = 0.0
 
 ### BEGIN SOLUTION
 # create the payoff matrix 
 A1 = np.array([10,12])
 MM = np.array([11,11])
 X = np.vstack([A1,MM])
 
 # create the vector of forwards 
 prc = np.array([10,10])
 rf = MM[0]/prc[1]-1
 fwd = prc*(1+rf)
 # create the payoff vector for the MM 
 A2 = np.array([-3,3])
 
 # solve the system of equations X@q = fwd
 Q = npl.inv(X)@fwd
 
 # compute the price of A2
 price = A2@Q/(1+rf)
 
 # you certaintly could have hard-coded the answer directly -- 
 # in this case you need to describe how you got your solution in 
 # the Markdown cell below!
 
 ### END SOLUTION
 return Q, price
sol4_4C()


(array([0.5, 0.5]), 4.844609562000683e-15)

# Q13
#### To find a yield to maturity of a zero-coupon bond it is sufficient to know (select as small information set as possible, that is, as few choices as needed to answer the question):
#### The current price of the bond and its maturity
#### The compounding convention for the yield to maturity to be found

# Q 14
#### The weighted (by present value of cash-flows relative to the bond price) average time to maturity of a bond portfolio is 11 years. What is the modified duration with respect to annually compounded YTM if the spot curve for annual compounding is flat at 10% p.a.
####  It is exactly 10.

#Q 15
####  There are two coupon bonds, A and B, both with semiannual coupons, both maturing in 1 year and having face value of 100. The coupon rate of A is 5%, and that of B is 10%. The prices are 94.65 and 99.3, respectively. Part A: Find the discount factors for 6 and 12 months. Find the continuously-compounded spot rates for 6 and 12 months (p.a.). Find the continuously-compounded forward rate for the period between 6 and 12 months (p.a.).


In [20]:
def sol5_3():
 """ 
 Return three outputs:
 1. numpy array with two discounf factors: 
 df = np.array([df6, df12])
 2. numpy array with two spot rates p.a. expressed as 
 decimal (e.g, 0.05 for 5% rate): 
 rate = np.array([r6, r12])
 3. a floating number with the forward rate p.a. expressed as 
 decimal (e.g, 0.05 for 5% rate): frate
 """ 
 # pre-allocate variables to return -- replace with your own the answers 
 df = np.full(2, np.nan)
 rate = np.full(2, np.nan)
 frate = 0.0
 
 ### BEGIN SOLUTION
 # we need to solve a system of equations: 
 # 2.5*df6 + 102.5*df12 = 94.65
 # 3*df6 + 103*df12 = 99.3
 b1 = np.array([2.5,102.5])
 b2 = np.array([5,105])
 X = np.vstack([b1,b2])
 P = np.array([94.65, 99.3 ])
 # the system can be written as X@df = P, where 
 #df = np.array([df6,df12])
 df = npl.inv(X)@P
 
 # discount factors need to be converted to spot rates now 
 # df = exp(-rate * t) => rate = -np.log(df)/t
 t = np.array([0.5,1])
 rate = -np.log(df)/t
 
 # the forward rate can be computed from either df or spot rates
 # frate = np.log(df6/df12)/(t12-t6)
 frate = np.log(df[0]/df[1])/0.5
 
 ### END SOLUTION
 return df, rate, frate
sol5_3()


(array([0.96, 0.9 ]), array([0.08164399, 0.10536052]), 0.12907704227511402)

### Part B [Bonus]:
#### Assume that in addition to the bonds A and B you get the bond C, which matures in 1.5 years, pays 5% semiannual coupon, has face value of 100 and costs 90. Find a replicating portfolio from the bonds that produces the cash-flow stream of 1,2,3 in 6,12, and 18 months. What is the price of this cash-flow?

In [21]:
def sol5_3BONUS():
 """ 
 Return two outputs:
 1. numpy array with three portfolio weights (adding up to 1): 
 ptf = np.array([w_A, w_B, w_C])
 2. a floating number with the price of the cash-flow: prc
 """ 
 # pre-allocate variables to return -- replace with your own the answers 
 ptf = np.full(3, np.nan)
 prc = 0.0
 
 ### BEGIN SOLUTION
 b1 = np.array([2.5,102.5,0])
 b2 = np.array([5,105,0])
 b3 = np.array([2.5,2.5,102.5])
 X = np.vstack([b1,b2,b3])
 P = np.array([94.65, 99.3, 90])
 
 # the system can be written as X.T@ptf = cf
 cf = np.array([1,2,3])
 ptf = npl.inv(X.T)@cf
 prc = ptf@P
 
 ### END SOLUTION
 return ptf,prc
sol5_3BONUS()


(array([-0.35073171,  0.36073171,  0.02926829]), 5.258048780487791)