In [1]:
# Import needed packages
# You may add or remove packages should you need them
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.datasets import load_iris
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.model_selection import KFold, LeaveOneOut, cross_val_score

# Set random seed
np.random.seed(0)

# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
# Set Seaborn aesthetic parameters to defaults
sns.set()

In [11]:
# Load the Iris dataset included with scikit-learn
dataset= load_iris()
df_iris = pd.DataFrame(dataset.data, columns=dataset.feature_names)
df_iris["target"] = dataset.target
df_iris.columns = [col.replace("(cm)", "").strip() for col in df_iris.columns]
df_iris

sepal length  sepal width  petal length  petal width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [12]:
df_iris.sample(n=10)

sepal length  sepal width  petal length  petal width  target
92            5.8          2.6           4.0          1.2       1
141           6.9          3.1           5.1          2.3       2
130           7.4          2.8           6.1          1.9       2
119           6.0          2.2           5.0          1.5       2
48            5.3          3.7           1.5          0.2       0
143           6.8          3.2           5.9          2.3       2
122           7.7          2.8           6.7          2.0       2
63            6.1          2.9           4.7          1.4       1
26            5.0          3.4           1.6          0.4       0
64            5.6          2.9           3.6          1.3       1

In [13]:
# Show 10 random samples

In [14]:
# now... implement the LDA (bear in mind that you do pass it the y's and it is supervised!)
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
df_lda = df_iris.drop(['target'], axis=1,)

In [15]:
# same process as always, identify your X's and your y's
X=df_iris.drop(["target"],axis=1)
y=df_iris["target"]


In [16]:
#train-test-split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [17]:
# Scale the X's
scaler = StandardScaler()

scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
# apply the lda transformation
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=1)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [19]:
# select 2 principal components
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
# take a look at the new axes for the data and plot them

In [ ]:
# what about the variability?

In [1]:
# Run a Random Forest Classifier with the transformed data


In [20]:
#Check the new acuracy! Is it higher or lower than what you obtain selecting 2 features and applying a Random Forest Directly?
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
Accuracy0.9666666666666667
